/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATH_H_RPCGEN
#define _MATH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
	int c;
};
typedef struct numbers numbers;

#define MATH_PROG 0x23451111
#define ADO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  int * add_1(numbers *, CLIENT *);
extern  int * add_1_svc(numbers *, struct svc_req *);
#define sqr 2
extern  int * sqr_1(int *, CLIENT *);
extern  int * sqr_1_svc(int *, struct svc_req *);
extern int math_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define add 1
extern  int * add_1();
extern  int * add_1_svc();
#define sqr 2
extern  int * sqr_1();
extern  int * sqr_1_svc();
extern int math_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATH_H_RPCGEN */
