/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "math.h"


void
math_prog_1(char *host, int x, int y, int z)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;
	int  *result_2;
	int  sqr_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATH_PROG, ADO_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	if(y != NULL && z != NULL){
		add_1_arg.a=x;
		add_1_arg.b=y;
		add_1_arg.c=z;
		result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else
		{
			printf("Add(%d,%d,%d):%d\n",x,y,z,*result_1);
		}
	}else{
		sqr_1_arg = x;
		result_2 = sqr_1(&sqr_1_arg, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else
		{
			printf("Sqr(%d):%d\n",x,*result_2);
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc == 3) {
		host = argv[1];
		math_prog_1 (host, atoi(argv[2]),NULL,NULL);		
	} else if (argc == 5){
		host = argv[1];
		math_prog_1 (host, atoi(argv[2]), atoi(argv[3]), atoi(argv[4]));
	}
	else {
		printf ("usage:\nSqr Syntax: %s server_host number\n", argv[0]);
		printf ("Add Syntax: %s server_host number number number\n", argv[0]);
		exit (1);
	}

exit (0);
}
