/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "math.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{

	static int  result;
	printf("add(%d, %d, %d) is called\n",argp->a, argp->b, argp->c);
	result = argp->a + argp->b + argp->c ;
	

	return &result;
}

int *
sqr_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("sqr(%d) is called\n",*argp);
	result = (*argp) * (*argp) ;

	return &result;
}
